import type { LegalDocument } from '../../types';

/**
 * Terms drafted from the app's actual behaviour and its in-app "Legal & Privacy" sheet.
 * Tokens such as {{operator}} are replaced at render time. Review with qualified legal counsel.
 */
export const termsAndConditions: LegalDocument = {
  title: 'Terms & Conditions',
  summary: 'These terms govern your use of the Flint app and website. Please read them carefully — especially the sections on your Tinder account and AI-generated messages.',
  sections: [
    {
      id: 'acceptance',
      title: 'Acceptance of these terms',
      blocks: [
        { type: 'p', text: 'These Terms & Conditions (“Terms”) are an agreement between you and {{operator}} (“Flint”, “we”, “us”). By creating an account, signing in or using the Flint app or website, you agree to these Terms and to our Privacy Policy. If you do not agree, do not use Flint.' },
      ],
    },
    {
      id: 'eligibility',
      title: 'Eligibility',
      blocks: [
        { type: 'p', text: 'You must be at least 18 years old and legally able to enter into this agreement. By using Flint you confirm that you meet these requirements. Accounts found to be operated by a minor will be terminated.' },
      ],
    },
    {
      id: 'the-service',
      title: 'The service',
      blocks: [
        {
          type: 'p',
          text: 'Flint is an AI assistant that operates your Tinder account on your instructions. Depending on your settings it can swipe on profiles, send opening messages and replies written by AI, follow up with matches, share contact details you have approved, and report activity back to you. Flint currently works with Tinder only.',
        },
        { type: 'p', text: 'Flint is not a dating service and does not introduce you to anyone. Flint does not guarantee any number of matches, conversations, dates or other outcomes.' },
      ],
    },
    {
      id: 'accounts',
      title: 'Your Flint account',
      blocks: [
        {
          type: 'list',
          items: [
            'Provide accurate information and keep your email address up to date; sign-in codes are sent to it.',
            'Keep access to your email and device secure. You are responsible for activity under your account.',
            'Tell us promptly at {{supportEmail}} if you believe your account has been accessed without permission.',
          ],
        },
      ],
    },
    {
      id: 'third-party-accounts',
      title: 'Your Tinder account and third-party platforms',
      blocks: [
        {
          type: 'p',
          text: 'When you connect Tinder, you authorise Flint to sign in to and act within your Tinder account on your behalf, including liking or passing on profiles and sending messages. You can stop this at any time.',
        },
        {
          type: 'p',
          text: 'Tinder is operated by a third party with its own terms of service and community guidelines. Those terms may restrict automated activity or the use of third-party tools. You are solely responsible for making sure your use of Flint complies with them. Using Flint may result in Tinder limiting, suspending or banning your account, and Flint is not responsible for any action a third-party platform takes.',
        },
        { type: 'p', text: 'Flint is not affiliated with, endorsed by or sponsored by Tinder or Match Group. Safety Mode and pacing features reduce the rate of activity but cannot guarantee how any platform will treat your account.' },
      ],
    },
    {
      id: 'ai-messages',
      title: 'AI-generated messages',
      blocks: [
        {
          type: 'p',
          text: 'Messages, replies and bios produced by Flint are generated by AI based on your settings and the information available in profiles and conversations. They are sent from your account and on your behalf. AI output can be inaccurate, inappropriate or not what you intended; you are responsible for the messages sent from your account and should review your conversations regularly.',
        },
        { type: 'p', text: 'If you enable contact sharing, Flint may share the Instagram handle or WhatsApp number you provided with matches. Only enable this if you are comfortable with that information being shared.' },
      ],
    },
    {
      id: 'acceptable-use',
      title: 'Acceptable use',
      blocks: [
        { type: 'p', text: 'You agree not to use Flint to:' },
        {
          type: 'list',
          items: [
            'harass, threaten, deceive or harm any person, or send hateful, sexually explicit or otherwise objectionable content;',
            'impersonate another person or misrepresent who you are;',
            'send spam, advertising or commercial solicitations, or run scams;',
            'contact or attempt to contact minors;',
            'collect, sell or misuse other people’s personal information, including information about your matches;',
            'break any law or regulation; or',
            'copy, reverse engineer, resell or interfere with Flint, or use it to build a competing product.',
          ],
        },
        { type: 'p', text: 'When you meet someone you connected with through a dating platform, take the usual safety precautions: meet in public, tell a friend where you will be, and never send money to someone you have not met.' },
      ],
    },
    {
      id: 'intellectual-property',
      title: 'Intellectual property',
      blocks: [
        { type: 'p', text: 'Flint, including its software, design, name and logo, belongs to {{operator}} and its licensors. We grant you a personal, non-exclusive, non-transferable, revocable licence to use Flint for your own non-commercial use in line with these Terms.' },
        { type: 'p', text: 'You keep ownership of content you provide, such as your bio and preferences, and grant us the rights needed to use it to operate Flint for you. Tinder and other third-party names are trademarks of their respective owners.' },
      ],
    },
    {
      id: 'third-party-services',
      title: 'Third-party services',
      blocks: [
        { type: 'p', text: 'Flint relies on third-party services such as Tinder, AI model providers, hosting, notification and cloud-browser providers. We are not responsible for third-party services, and your use of them may be subject to their own terms.' },
      ],
    },
    {
      id: 'fees',
      title: 'Fees',
      blocks: [
        { type: 'p', text: 'Any paid features, trials or usage limits will be described in the app before you are charged. Purchases made through the Apple App Store or Google Play are subject to their billing terms.' },
        { type: 'owner', text: 'pricing, trial terms, renewal and refund policy if Flint offers paid plans. No pricing information exists in the repository.' },
      ],
    },
    {
      id: 'availability',
      title: 'Service availability and changes',
      blocks: [
        { type: 'p', text: 'We work to keep Flint available, but it is provided on an “as available” basis. Flint depends on third-party platforms that can change without notice, so features may stop working, be limited or change. We may add, modify or remove features, and set usage limits, at any time.' },
      ],
    },
    {
      id: 'disclaimers',
      title: 'Disclaimers',
      blocks: [
        { type: 'p', text: 'To the fullest extent permitted by law, Flint is provided “as is” without warranties of any kind, whether express or implied, including warranties of merchantability, fitness for a particular purpose and non-infringement. We do not warrant that Flint will be uninterrupted, error-free or that it will achieve any particular result.' },
      ],
    },
    {
      id: 'limitation-of-liability',
      title: 'Limitation of liability',
      blocks: [
        {
          type: 'p',
          text: 'To the fullest extent permitted by law, Flint and its operators will not be liable for any indirect, incidental, special, consequential or punitive damages, or for any loss of data, accounts, opportunities or goodwill, including any restriction or loss of a third-party account, arising from your use of Flint. Nothing in these Terms limits liability that cannot be limited under applicable law.',
        },
        { type: 'owner', text: 'any cap on liability and whether an indemnity clause is required, with advice from legal counsel for the jurisdictions you operate in.' },
      ],
    },
    {
      id: 'termination',
      title: 'Suspension and termination',
      blocks: [
        { type: 'p', text: 'You can stop using Flint at any time and delete your account in the app. We may suspend or terminate your access if you break these Terms, if required by law, or to protect users, third parties or the service. Sections that by their nature should survive termination will continue to apply.' },
      ],
    },
    {
      id: 'changes',
      title: 'Changes to these terms',
      blocks: [
        { type: 'p', text: 'We may update these Terms from time to time. We will post the new version on this page with a new effective date and, for significant changes, let you know in the app or by email. Continuing to use Flint after changes take effect means you accept the updated Terms.' },
      ],
    },
    {
      id: 'governing-law',
      title: 'Governing law',
      blocks: [{ type: 'p', text: 'These Terms are governed by the laws of {{governingLaw}}, without regard to its conflict-of-law rules, except where the law of your country of residence requires otherwise.' }],
    },
    {
      id: 'contact',
      title: 'Contact',
      blocks: [
        { type: 'p', text: 'Questions about these Terms? Email {{supportEmail}}.' },
        { type: 'p', text: 'Postal address: {{address}}' },
      ],
    },
  ],
};
