[program:chromium]
environment=HOME="/home/%(ENV_USER)s",USER="%(ENV_USER)s",DISPLAY="%(ENV_DISPLAY)s"
command=bash -c "rm -rf /home/neko/.config/google-chrome/SingletonLock /home/neko/.config/google-chrome/Default/SingletonLock /home/neko/.config/google-chrome/Default/GCM\ Store || true; exec /usr/bin/google-chrome \
  --no-sandbox \
  --window-position=0,0 \
  --window-size=416,912 \
  --display=%(ENV_DISPLAY)s \
  --user-data-dir=/home/neko/.config/google-chrome \
  --profile-directory=Default \
  --disable-profile-picker \
  --enable-logging=stderr \
  --v=1 \
  --no-first-run \
  --start-maximized \
  --force-dark-mode \
  --force-device-scale-factor=0.5 \
  --user-agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36' \
  --disable-file-system \
  --disable-gpu \
  --disable-software-rasterizer \
  --disable-dev-shm-usage \
  --disable-dbus \
  --disable-background-networking \
  --disable-component-update \
  --disable-default-apps \
  --no-pings \
  --disable-gcm \
  --load-extension=/src/extension \
  "${NEKO_START_URL:-https://tinder.com}""
stopsignal=INT
autorestart=true
priority=800
user=%(ENV_USER)s
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
redirect_stderr=true

[program:openbox]
environment=HOME="/home/%(ENV_USER)s",USER="%(ENV_USER)s",DISPLAY="%(ENV_DISPLAY)s"
command=/usr/bin/openbox --config-file /etc/neko/openbox.xml
autorestart=true
priority=300
user=%(ENV_USER)s
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
redirect_stderr=true
