
[program:chromium]
environment=HOME="/home/%(ENV_USER)s",USER="%(ENV_USER)s",DISPLAY="%(ENV_DISPLAY)s"
command=bash -c "rm -rf /home/neko/.config/chromium/SingletonLock /home/neko/.config/chromium/Default/SingletonLock || true; exec /usr/bin/chromium \
  --no-sandbox \
  --load-extension=/src/extension \
  --window-position=0,0 \
  --window-size=416,912 \
  --display=%(ENV_DISPLAY)s \
  --user-data-dir=/home/neko/.config/chromium \
  --profile-directory=Default \
  --disable-profile-picker \
  --no-first-run \
  --start-maximized \
  --force-device-scale-factor=1.2      \
  --user-agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36' \
  --disable-gpu \
  --disable-software-rasterizer \
  --disable-dev-shm-usage \
  --disable-background-networking \
  --disable-default-apps \
  --no-pings \
  --remote-debugging-port=9222 \
  --remote-debugging-address=0.0.0.0 \
  "${NEKO_START_URL:-https://bumble.com/get-started}""
stopsignal=INT
autorestart=true
priority=800
user=%(ENV_USER)s
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
redirect_stderr=true

[program:openbox]
environment=HOME="/home/%(ENV_USER)s",USER="%(ENV_USER)s",DISPLAY="%(ENV_DISPLAY)s"
command=/usr/bin/openbox --config-file /etc/neko/openbox.xml
autorestart=true
priority=300
user=%(ENV_USER)s
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
redirect_stderr=true
